### ISSUE TITLE
Plugin crash with mirco 1.3.4

### ISSUE THREAD

**Issue by id777** [boombuler/microsnippets#7]
Hi, i just installed fresh micro 1.3.4, then this plugin. (linux 64 bit version).
After when I typed keyword, press alt+s (this strange, why alt+s? Everywhere using Tab) snippet inserts, but then, if try to type any key, there is crash:

```
snippets:314: attempt to index a non-table object(nil)
stack traceback:
        snippets:314: in main chunk
        [G]: ?

Press enter to continue
```

**Comment by id777** [comment]
I noticed same issue https://github.com/boombuler/microsnippets/issues/4 it seems like it's was fixed.. But why I still get this error?

**Comment by boombuler** [comment]
Maybe because I didn't make a new release yet. Could you try with the current master branch?

**Comment by id777** [comment]
@boombuler 
Yes, it works from master. Please make a new release.
Also there is bug. When I press alt+S after keyword, I can change position using alt+W. But if I firstly edit first placeholder, then alt+W didn't work.

Also, how I can change keybindings? Everywhere is the world using simple Tab, to create snippet and going throught all placeholders.

**Comment by boombuler** [comment]
Hi, new release is published... Sorry for taking such a long time...
